#ifndef EVERFLOW_ALGOS_LEETCODE_1060_MISSING_ELEMENT_IN_SORTED_ARRAY_H_
#define EVERFLOW_ALGOS_LEETCODE_1060_MISSING_ELEMENT_IN_SORTED_ARRAY_H_

namespace algos {




} // namespace algos

#endif //EVERFLOW_ALGOS_LEETCODE_1060_MISSING_ELEMENT_IN_SORTED_ARRAY_H_
