#ifndef EVERFLOW_ALGOS_LEETCODE_946_VALIDATE_STACK_SEQUEUES_H_
#define EVERFLOW_ALGOS_LEETCODE_946_VALIDATE_STACK_SEQUEUES_H_

namespace algos {




} // namespace algos

#endif //EVERFLOW_ALGOS_LEETCODE_946_VALIDATE_STACK_SEQUEUES_H_
