//
// Created by Luke Skywalker on 2021/7/17.
//

#ifndef EVERFLOW_ALGOS_SEARCH_THE_UBIQUITOUS_BINARY_SEARCH_H_
#define EVERFLOW_ALGOS_SEARCH_THE_UBIQUITOUS_BINARY_SEARCH_H_

#endif //EVERFLOW_ALGOS_SEARCH_THE_UBIQUITOUS_BINARY_SEARCH_H_
